spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:duo_db}?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890abcdefghijklmnopqrstuvwxyz}
  expiration: ${JWT_EXPIRATION:86400}

logging:
  level:
    com.example: INFO
    org.springframework: WARN
    org.hibernate: WARN
  file:
    name: logs/application.log
