spring:
  application:
    name: backend-service
  datasource:
    url: jdbc:mysql://localhost:3306/duo_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  expiration: 86400 # 24小时（秒）
  header: Authorization

logging:
  level:
    '[com.example]': DEBUG
    '[org.springframework]': INFO
