spring:
  datasource:
    url: jdbc:mysql://mysql:3306/duo_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379
      password: 
      database: 0

server:
  port: 8080

jwt:
  secret: mySecretKey1234567890abcdefghijklmnopqrstuvwxyz
  expiration: 86400

logging:
  level:
    com.example: INFO
    org.springframework: INFO
